apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: golang-build-template
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Create dummy Go app
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          mkdir hello && cd hello
          go mod init hello
          echo 'package main; import "fmt"; func main() { fmt.Println("Hello, CloudBees!") }' > main.go
          go build -v .
          ./hello
